### ISSUE TITLE
Cannot download tensorflow graph file

### ISSUE THREAD

**Issue by forendev** [Chenyang-ZHU/YOLOv3-Based-Face-Detection-Tracking#1]
Hi, 
I am very interested in your work on yolov3, and I wanted to test your code.
Unfortunately, I cannot download the tensoflow grah file from https://pan.baidu.com.

Would you agree to upload it to another site like dropbox or google drive, please?

Regards.

**Comment by forendev** [comment]
Hi,
finally, no need to put this file elsewhere, I could get it.
Regards

**Comment by leo7r** [comment]
@forendev do you have the file uploaded somewhere different than pan.baidu? I'm having trouble downloading from that site
